#!/bin/bash
#PBS -l nodes=1:ppn=16:xk
#PBS -N SingleFrame 
#PBS -l walltime=04:00:00
#PBS -e result/$PBS_JOBNAME.$PBS_JOBID.err
#PBS -o result/$PBS_JOBNAME.$PBS_JOBID.out
#PBS -r bea
#PBS -M mohans2@illinois.edu
cd /u/training/tra437/scratch/CS598/Pytorch_AR/
. /opt/modules/default/init/bash
module load bwpy/2.0.0-pre2
module load cudatoolkit
aprun -n 1 -N 1 python CS598_Mohan_Sun_HW9_Single_Frame.py
